### ISSUE TITLE
How to use video_url from the snapshot entity?

### ISSUE THREAD

**Issue by bikeymouse** [JimStar/reolink_cctv#137]
Hi,

Thanks for you great work! 

I have a question though understanding how things are implemented: I'm trying to use the video_url attribute so I can redirect to the real-time video stream in a notification.

If I use it in a service call like this, I get a "non authorized" (401): 
```
service: notify.my_mobile_phone
data:
  message: Snapshot-Video
  data:
    image: >-
      https://external-url-to-homeassistant{{state_attr('camera.reolink_doorbell_snapshots','video_url')}}  
```

However If I basically do the same with the entire_picture attribute this all works well and access is allowed:

```
service: notify.my_mobile_phone
data:
  message: Snapshot-Entiry-Picture
  data:
    image: >-
      https://external-url-to-homeassistant{{state_attr('camera.reolink_doorbell_snapshots',
      'entity_picture')}}

```
(FYI: the same "non authorized" appears if I try this with the "video_thumbnail" attribute).

Now If I look at the contents of the 'entity_picture' attribute, I see it contains the path, including the access-token:
`api/camera_proxy/camera.reolink_doorbell_snapshots?token=xxxxxx-token-xxxxx`

However with the video_url (and the video_thumbnail) attribute the content is a path without an access-token:
`/api/reolink_cctv/vod/e0174d9a468dc7fed9f1241a84745739/0/Mp4Record%2F2022-12-26%2FRecS03_xxxxxxxx.mp4`

How does authorization work with this video_url, is that basically done by creating a long path to the video? (I tried adding the token to the path however doesn't seem to help).

So question is, what am I doing wrong here?
