### ISSUE TITLE
command "SetEmail" error

### ISSUE THREAD

**Issue by garry0garry** [JimStar/reolink_cctv#30]
Home Assistant 2022.10.4, Frontend 20221010.0, HACS 1.28.2, Reolink IP NVR/cameras 0.0.15

Reolink RLC-520A hw IPC_523128M5MP v3.1.0.951_22041566 - 9 pcs.
Reolink RLC-520A hw IPC_523128M5MP_V2 v3.1.0.1228_22082201 - 2 pcs.
Reolink RLC-511WA hw IPC_523128M5MP v3.1.0.956_22041509 - 1 pc.

Settings:
HTTP, rtsp
Motion sensor off delay (seconds) - 60
Connection timeout (seconds) - 120

```
logger:
  default: warning
  logs:
    homeassistant.core: warning
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/switch.py:182
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 12:05:55 (12 occurrences)
Last logged: 12:07:33

Host 192.168.50.63:80: command "SetEmail" error.
Host 192.168.50.162:80: command "SetEmail" error.
Host 192.168.50.72:80: command "SetEmail" error.
Host 192.168.50.37:80: command "SetEmail" error.
Host 192.168.50.14:80: command "SetEmail" error.

```
Debug-log in attachment.
[home-assistant.copy.zip](https://github.com/JimStar/reolink_cctv/files/9808810/home-assistant.copy.zip)
