### ISSUE TITLE
Set backlight service not changing anything

### ISSUE THREAD

**Issue by etamtlosz** [JimStar/reolink_cctv#4]
**Describe the bug**
I'm using a RLN8-410 with 4 x RLC-810A. I've configured the integration connecting to the NVR, not to each camera individually.
When trying to use the `Reolink IP NVR/camera: Set backlight` service none of the cameras are changing. It does not matter what I choose: blacklightcontrol, dynamicrangecontrol or off.
The NVR has the HW version N3MB01 running fw v3.0.0.200_22081500, while the cameras are hw version IPC_523128M8MP, running v3.1.0.956_22041503.

**Comment by JimStar** [comment]
Could you please enable the debug logging and attach the log content after you tried to use that service?
```
logger:
  default: warning
  logs:
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```
